version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: cobamovil-postgres
    environment:
      POSTGRES_DB: cobamovil_db
      POSTGRES_USER: cobamovil_user
      POSTGRES_PASSWORD: cobamovil_pass
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/main/resources/db/migration:/docker-entrypoint-initdb.d
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cobamovil_user -d cobamovil_db"]
      interval: 30s
      timeout: 10s
      retries: 3

  app:
    build: .
    container_name: cobamovil-backend
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DATABASE_URL: jdbc:postgresql://postgres:5432/cobamovil_db
      DATABASE_USERNAME: cobamovil_user
      DATABASE_PASSWORD: cobamovil_pass
      JWT_SECRET: ${JWT_SECRET:-mySecretKey123456789012345678901234567890}
      JWT_EXPIRATION: ${JWT_EXPIRATION:-86400}
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data: