version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: cobamovil-postgres
    environment:
      POSTGRES_DB: cobamovil_db
      POSTGRES_USER: cobamovil_user
      POSTGRES_PASSWORD: cobamovil_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: