spring:
  datasource:
    url: jdbc:postgresql://dpg-d31bpummcj7s7389dn60-a/cobamovil_db
    username: cobamovil_user
    password: 3XRLm2xEv9mGpBwo59woLXo4lVZDWKEX
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  flyway:
    enabled: true
    url: jdbc:postgresql://dpg-d31bpummcj7s7389dn60-a/cobamovil_db
    user: cobamovil_user
    password: 3XRLm2xEv9mGpBwo59woLXo4lVZDWKEX
